pipeline {
  // Se ejecuta en cualquier agente disponible
  agent any
  
  tools {
    // Usar Maven 3.9.1 para construir el proyecto
    maven 'Maven_home'
    
  }
  
  stages {
    stage('Build and package') {
      steps {
        // Clonar el repositorio de GitHub y verificar la rama principal
        checkout([$class: 'GitSCM', branches: [[name: '*/main']], 
                  extensions: [], 
                  userRemoteConfigs: [[credentialsId: 'cf6403c6-af6a-4503-8642-843f5803307f', 
                                       url: 'https://github.com/antonio395/Jenkins_']]])
        
        // Limpiar el proyecto y compilarlo con Maven
        sh 'mvn clean package -f Stripe_/Stripe_/pom.xml -DskipTests'
        

      }
    }
  }
}

